title = "Top Crosslinked Subreddits"
baseURL = "/"
languageCode = "en-us"
publishDir = "docs"

[permalinks]
  pages = "/r/:title/"

[params]
  # email = "myemail"
  github = "dankleiman"
  #gitlab = "gitlab id"
  twitter = "dan_kleiman"
  #linkedin = "linkedin id"  